#!/usr/bin/env python3
"""
TASK 6.1B-REPAIR-1: Restore occurrence-based mention counting.
Reads registry.md, extracts canonical names, scans sources for exact occurrences,
and generates provisional codex candidate pages in --write mode.
"""
import argparse
import glob
import os
import re
import sys
from datetime import date

BASE_DIR = "/home/mytruelove/Downloads/obsidianburdenNov25/_mrlore"
REGISTRY_PATH = os.path.join(BASE_DIR, "wiki/registry.md")
SOURCES_DIR = os.path.join(BASE_DIR, "wiki/sources")
CODEX_DIR = os.path.join(BASE_DIR, "wiki/codex_candidates")

EXPECTED_HEADER_COLS = ["Canonical Name", "Canon State", "Variants", "First Source", "Page"]

def slugify_filename(name):
    """Deterministically convert canonical name to safe filename."""
    s = name.lower()
    s = s.replace(" ", "_").replace("/", "_").replace("'", "_").replace(":", "_")
    s = re.sub(r'[^a-z0-9_-]', '', s)
    s = re.sub(r'_+', '_', s)
    s = s.strip('_')
    if not s:
        s = "unnamed_entity"
    return s

def parse_registry(path):
    """Parse markdown table and extract unique canonical names from column 1."""
    canonical_names = []
    try:
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"ERROR: Registry not found at {path}", file=sys.stderr)
        sys.exit(1)

    header_index = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [p.strip() for p in stripped.split("|")[1:-1]]
        if len(parts) >= 2 and parts[0] == EXPECTED_HEADER_COLS[0] and parts[1] == EXPECTED_HEADER_COLS[1]:
            header_index = i
            break

    if header_index is None:
        print("ERROR: Expected registry table header not found.", file=sys.stderr)
        sys.exit(1)

    for line in lines[header_index + 1:]:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        if all("---" in part or not part.strip() for part in stripped.split("|")[1:-1]):
            continue

        parts = [p.strip() for p in stripped.split("|")[1:-1]]
        if len(parts) > 0 and parts[0]:
            canonical_names.append(parts[0])

    seen = set()
    unique = []
    for name in canonical_names:
        if name not in seen:
            seen.add(name)
            unique.append(name)

    return sorted(unique)

def scan_sources_for_entity(entity_name, sources_dir):
    """Return (total_mentions, list_of_source_basenames) for exact entity_name."""
    total_mentions = 0
    found_sources = []
    for src_path in sorted(glob.glob(os.path.join(sources_dir, "*.md"))):
        with open(src_path, "r", encoding="utf-8") as f:
            content = f.read()
        c = content.count(entity_name)
        if c > 0:
            total_mentions += c
            found_sources.append(os.path.basename(src_path))
    return total_mentions, found_sources

def generate_candidate_page(name, mention_count, source_files):
    """Generate deterministic provisional candidate markdown."""
    today = date.today().isoformat()
    source_refs = "\n".join(f"- `wiki/sources/{s}`" for s in source_files) if source_files else "- None detected"
    return f"""---
status: candidate
canon_state: provisional
review_only: true
generated_date: {today}
entity_name: "{name}"
mention_count: {mention_count}
---

# {name} (Codex Candidate)

> **REVIEW ONLY**: This page is a provisional candidate generated by MrLore Phase 6. It requires human approval before canon promotion.

## Source Mention Count
- Total occurrences across source summaries: `{mention_count}`

## Source References
{source_refs}

## Unresolved Questions
- [ ] Confirm canonical classification and tier
- [ ] Verify timeline placement relative to active arcs
- [ ] Identify behavioral, thematic, or factional constraints
- [ ] Check against CONT-0001/CONT-0002 for alias drift

## Human Review Checklist
- [ ] Spelling matches current CANON decision
- [ ] No contradiction with existing wiki synthesis
- [ ] Source references accurately reflect corpus usage
- [ ] Approve for promotion to wiki/species/wiki/terms/wiki/factions OR archive candidate
"""

def main():
    parser = argparse.ArgumentParser(description="Codex candidate enumerator & writer")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--dry-run", action="store_true", help="Print candidate info only. No files created.")
    group.add_argument("--write", action="store_true", help="Generate review-only candidate pages.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing candidate pages.")
    args = parser.parse_args()

    entities = parse_registry(REGISTRY_PATH)

    print(f"[MODE] {'DRY-RUN' if args.dry_run else 'WRITE'}")
    print(f"[ENTITIES] {len(entities)} loaded from registry")
    print("-" * 60)

    if args.dry_run:
        for name in entities:
            count, sources = scan_sources_for_entity(name, SOURCES_DIR)
            slug = slugify_filename(name)
            rel_path = os.path.join("wiki", "codex_candidates", f"{slug}.md")
            print(f"Canonical Name: {name}")
            print(f"  Mention Count: {count}")
            print(f"  Intended Output Path (relative to _mrlore): {rel_path}")
            print("-" * 60)
        print("[DRY-RUN] Complete. EXIT 0")
        sys.exit(0)

    # WRITE MODE
    os.makedirs(CODEX_DIR, exist_ok=True)
    created = 0
    skipped = 0
    forced = 0

    for name in entities:
        count, sources = scan_sources_for_entity(name, SOURCES_DIR)
        slug = slugify_filename(name)
        out_path = os.path.join(CODEX_DIR, f"{slug}.md")

        if os.path.exists(out_path):
            if not args.force:
                skipped += 1
                print(f"[SKIP] {out_path} (use --force to overwrite)")
                continue
            forced += 1
            print(f"[FORCE] {out_path}")

        content = generate_candidate_page(name, count, sources)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        created += 1
        print(f"[WRITE] {out_path}")

    print("-" * 60)
    print(f"[SUMMARY] Created: {created} | Forced: {forced} | Skipped: {skipped}")
    print("[WRITE] Complete. EXIT 0")
    sys.exit(0)

if __name__ == "__main__":
    main()